"""Copy crew prompts from crews/<crew>/04-prompts/*.md into the workflows that use them.

Usage: python3 scripts/embed-prompts.py [workflow file...]   (default: every workflow)

A Code node whose notes read `prompts: <crew> <name> <name>...` gets its code replaced by one
item holding each named prompt (the crew's _shared.md, then <name>.md) and `version`, a hash of
all of that crew's prompt files, which the workflow records next to what the prompts produced.
Edit the .md files, run this, then push the workflow.
"""

import hashlib
import json
import sys
from pathlib import Path

from n8n_sync import ROOT, WORKFLOWS, write

HEADER = "// Generated by scripts/embed-prompts.py from crews/{crew}/04-prompts/. Edit the .md files, not this.\n"


def prompts(crew):
    folder = ROOT / "crews" / crew / "04-prompts"
    files = {p.stem: p.read_text(encoding="utf-8").strip() for p in sorted(folder.glob("*.md"))}
    version = hashlib.sha1("\n".join(f"{k}\n{v}" for k, v in files.items()).encode()).hexdigest()[:8]
    return files, version


def embed(path):
    workflow = json.loads(path.read_text(encoding="utf-8"))
    changed = False
    for node in workflow.get("nodes", []):
        notes = (node.get("notes") or "").split()
        if node.get("type") != "n8n-nodes-base.code" or notes[:1] != ["prompts:"] or len(notes) < 3:
            continue
        crew, names = notes[1], notes[2:]
        files, version = prompts(crew)
        missing = [n for n in names if n not in files]
        if missing:
            sys.exit(f"{path}: node {node['name']!r} names missing prompts: {', '.join(missing)}")
        out = {"version": version, **{n: f"{files['_shared']}\n\n{files[n]}" for n in names}}
        code = HEADER.format(crew=crew) + f"return [{{ json: {json.dumps(out, ensure_ascii=False, indent=2)} }}];"
        if node["parameters"].get("jsCode") != code:
            node["parameters"]["jsCode"] = code
            changed = True
    if changed:
        write(path, workflow)
        print(f"embedded {path.relative_to(ROOT)}")


def main():
    paths = [Path(p).resolve() for p in sys.argv[1:]] or sorted(WORKFLOWS.rglob("*.json"))
    for path in paths:
        embed(path)


if __name__ == "__main__":
    main()
